name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # 4. Build Vite project
      - name: Build project
        run: npm run build
        working-directory: ./frontend

      # 5. Deploy dist folder to EC2
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Copy dist folder instead of build
          rsync -avz --delete ./frontend/dist/ ${EC2_USER}@${EC2_HOST}:${TARGET_PATH}

          # Reload nginx on EC2
          ssh ${EC2_USER}@${EC2_HOST} << 'EOF'
            sudo systemctl reload nginx
          EOF
